"""Initial migration

Revision ID: 37fcfbd00d8a
Revises: 
Create Date: 2026-04-21 22:11:42.382418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fcfbd00d8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html5_sessions',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=255), nullable=False),
    sa.Column('pod', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username', 'connection_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('extauth', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('sat', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.BigInteger(), nullable=False),
    sa.Column('datestart', sa.BigInteger(), nullable=False),
    sa.Column('diskusage', sa.Float(), nullable=False),
    sa.Column('html5', sa.Boolean(), nullable=False),
    sa.Column('folder', sa.String(length=512), nullable=False),
    sa.Column('lab', sa.String(length=512), nullable=True),
    sa.Column('pod', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('session_expires', sa.BigInteger(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('labs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('scripttimeout', sa.Integer(), nullable=False),
    sa.Column('countdown', sa.Integer(), nullable=False),
    sa.Column('linkwidth', sa.String(length=8), nullable=False),
    sa.Column('grid', sa.Boolean(), nullable=False),
    sa.Column('lock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('lab_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pods')
    op.drop_table('labs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('html5_sessions')
    # ### end Alembic commands ###
